name: Cameron Pieratt
favicon: null
layout_spectrum: 0.25508
typography_spectrum: 0.38456
title: Cameron Pieratt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0a235c'
    - '#1f49ad'
    - '#70a2df'
    - '#bad3f2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
